language: cpp
compiler:
  - gcc
  - clang
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev
script: mkdir build && cd build && cmake -G "Unix Makefiles" .. && make
notifications:
  email:
    recipients:
      - clement.michaud34@gmail.com
    on_success: change
    on_failure: always
