language: cpp

services:
  - docker

before_install:
  - docker build -t open-intent-build .

script:
  - docker create --name open-intent-source-volume -v $(pwd):/src ubuntu:xenial /bin/false
  - docker run --rm --volumes-from open-intent-source-volume -v /var/run/docker.sock:/var/run/docker.sock -v $(which docker):/usr/bin/docker open-intent-build /src/scripts/build_and_test.sh

notifications:
  email:
    recipients:
      - clement.michaud34@gmail.com
      - sergei.kireev@hotmail.fr
    on_success: change
    on_failure: always
